# Generated by Django 3.0.3 on 2020-03-18 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_appointments',
            name='appointment_time_from',
            field=models.PositiveIntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_appointments',
            name='appointment_time_to',
            field=models.PositiveIntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='slots',
            field=models.CharField(blank=True, choices=[('11:00 - 11:30', '11:00 - 11:30'), ('11:30 - 12:00', '11:30 - 12:00'), ('12:00 - 12:30', '12:00 - 12:30'), ('12:30 - 01:00', '12:30 - 01:00'), ('02:00 - 02:30', '02:00 - 02:30'), ('02:30 - 03:00', '02:30 - 03:00'), ('03:00 - 03:30', '03:00 - 03:30'), ('03:30 - 04:00', '03:30 - 04:00'), ('04:30 - 05:00', '04:30 - 05:00'), ('05:30 - 06:00', '05:30 - 06:00')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='add_appointments',
            name='appointment_date',
            field=models.DateField(verbose_name='Appointment Date: yyyy-mm-dd'),
        ),
        migrations.AlterField(
            model_name='add_appointments',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
