# Generated by Django 3.0.3 on 2020-04-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200418_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_appointments',
            name='available_slots',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
